name:                language-bruh
version:             0.0.1.0
github:              "yuuriosity/language-bruh"
license:             BSD3
author:              "Yulia Gorshkova"
maintainer:          "yuuriosity@gmail.com"
copyright:           "2022 Yulia Gorshkova"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/yuuriosity/language-bruh#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
  - OverloadedStrings
  - PatternSynonyms

library:
  source-dirs: src
  dependencies:
  - text

tests:
  language-bruh-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - language-bruh
